### ISSUE TITLE
Does not work on linux mint 18.3 or 19

### ISSUE THREAD

**Issue by IAMtheIAM** [sidneys/desktop-dimmer#35]
Run the install, then Running `desktop-dimmer` gets this immediately
```
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/user/.nvm/versions/node/v8.11.3/lib/node_modules/desktop-dimmer/lib/logger'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v8.11.3/lib/node_modules/desktop-dimmer/bin/cli.js:36:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

Linux mint 18.3 and also tried mint 19

**Comment by hawkins** [comment]
Same error on Windows 10.

```
$ desktop-dimmer
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Users\blank\AppData\Roaming\npm\node_modules\desktop-dimmer\lib\logger'
```

**Comment by IAMtheIAM** [comment]
@hawkins It appears to be busted all together if both windows and linux get the same error. Hopefully the maintainers can take a look at this and make a patch for us.

**Comment by JosephAntony1** [comment]
Yeah I ran into this too

**Comment by 7--** [comment]
I had the same issue on Ubuntu 18 when trying to install with the command line. But when I used the .deb file under Releases it worked for me. https://github.com/sidneys/desktop-dimmer/releases

Edit:
I couldn't get it to work on Ubuntu 20.04. brightness-controller is a better alternative app. 
https://askubuntu.com/questions/1237701/how-do-you-dim-desktop-screen-20-04-lts?noredirect=1#comment2084405_1237701
